include:
  - package:flutter_lints/flutter.yaml
  - package:very_good_analysis/analysis_options.yaml

# https://dart.dev/tools/analysis#changing-the-severity-of-rules
analyzer:
  errors:
    depend_on_referenced_packages: error
    # Now we adjust the maximum line to 120
    lines_longer_than_80_chars: ignore
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.mapper.dart
    - packages/**

formatter:
  page_width: 120

linter:
  rules:
    flutter_style_todos: false